BASE_URL=https://api.escuelajs.co
category.name=Electronics from Config
category.image=https://placehold.co/600x400
category.endpoint=/api/v1/categories
Limit=12
category.by.id.endpoint=/api/v1/categories/{id}
category.by.slug.endpoint=/api/v1/categories/slug/{slug}

product.endpoint=/api/v1/products

product.id.endpoint=/api/v1/products/{id}