BASE_URL=https://api.escuelajs.co

# Category Configs
categoryName=Electronics from Config
categoryImage=https://placehold.co/600x400
category=/api/v1/categories
categoryId=/api/v1/categories/{id}
categorySlug=/api/v1/categories/slug/{slug}
Limit=12
report.name=Automation Tester: Giorgi Mikeladze - Reports
report.title=Test Execution Report
env=QA
# Product Configs
product=/api/v1/products
productId=/api/v1/products/{id}

# Assertion Configs
response.time=20000