BASE_URL=https://api.escuelajs.co

# Category Configs
category.name=Electronics from Config
category.image=https://placehold.co/600x400
category.endpoint=/api/v1/categories
category.by.id.endpoint=/api/v1/categories/{id}
category.by.slug.endpoint=/api/v1/categories/slug/{slug}
Limit=12

# Product Configs
product.endpoint=/api/v1/products
product.id.endpoint=/api/v1/products/{id}

# Assertion Configs
response.time=20000