BASE_URL=https://api.escuelajs.co

# Category Configs
categoryName=Electronics from Config
productName=ElectronicsProduct from Config
categoryImage=https://placehold.co/600x400
maxBodyLengthInMessage=1500
Limit=6

# Assertion Configs
response.time=5000