# Base Settings
base.url=https://api.escuelajs.co

# Category Configs
category.name=Electronics from Config
product.name=ElectronicsProduct from Config
category.image=https://placehold.co/600x400
max.body.length.in.message=1500
limit=6

# Assertion Configs
response.time=10000

# User Configs
user.avatar=https://api.lorem.space/image/face?w=640&h=480&r=867
user.email=randomNameForMail

max.step.title=250
report.engine=extent

email=john@mail.com
password=changeme
