BASE_URL=https://api.escuelajs.co

# Category Configs
categoryName=Electronics from Config
categoryImage=https://placehold.co/600x400
Limit=12
report.name=Automation Tester: Giorgi Mikeladze - Reports
report.title=Test Execution Report
env=QA

# Assertion Configs
response.time=20000